// LOGIN FACEBOOK
export const LOG_IN_FACEBOOK_REQUEST = 'LOG_IN_FACEBOOK_REQUEST';
export const LOG_IN_FACEBOOK_SUCCESS = 'LOG_IN_FACEBOOK_SUCCESS';
export const LOG_IN_FACEBOOK_ERROR = 'LOG_IN_FACEBOOK_ERROR';

// LOGIN GOOGLE
export const LOG_IN_GOOGLE_REQUEST = 'LOG_IN_GOOGLE_REQUEST';
export const LOG_IN_GOOGLE_SUCCESS = 'LOG_IN_GOOGLE_SUCCESS';
export const LOG_IN_GOOGLE_ERROR = 'LOG_IN_GOOGLE_ERROR';

// LOGOUT
export const LOG_OUT_REQUEST = 'LOG_OUT_REQUEST';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const LOG_OUT_ERROR = 'LOG_OUT_ERROR';

// COMMUNITIES
export const LOAD_COMMUNITIES_REQUEST = 'LOAD_COMMUNITIES_REQUEST';
export const LOAD_COMMUNITIES_SUCCESS = 'LOAD_COMMUNITIES_SUCCESS';
export const LOAD_COMMUNITIES_ERROR = 'LOAD_COMMUNITIES_ERROR';

export const ADD_COMMUNITY_REQUEST = 'ADD_COMMUNITY_REQUEST';
export const ADD_COMMUNITY_SUCCESS = 'ADD_COMMUNITY_SUCCESS';
export const ADD_COMMUNITY_ERROR = 'ADD_COMMUNITY_ERROR';

export const CREATE_COMMUNITY_REQUEST = 'CREATE_COMMUNITY_REQUEST';
export const CREATE_COMMUNITY_SUCCESS = 'CREATE_COMMUNITY_SUCCESS';
export const CREATE_COMMUNITY_ERROR = 'CREATE_COMMUNITY_ERROR';

export const FIND_COMMUNITY_REQUEST = 'FIND_COMMUNITY_REQUEST';
export const FIND_COMMUNITY_SUCCESS = 'FIND_COMMUNITY_SUCCESS';
export const FIND_COMMUNITY_ERROR = 'FIND_COMMUNITY_ERROR';

export const LEAVE_COMMUNITY_REQUEST = 'LEAVE_COMMUNITY_REQUEST';
export const LEAVE_COMMUNITY_SUCCESS = 'LEAVE_COMMUNITY_SUCCESS';
export const LEAVE_COMMUNITY_ERROR = 'LEAVE_COMMUNITY_ERROR';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

// ANNOUNCEMENTS
export const LOAD_ANNOUNCEMENTS_REQUEST = 'LOAD_ANNOUNCEMENTS_REQUEST';
export const LOAD_ANNOUNCEMENTS_SUCCESS = 'LOAD_ANNOUNCEMENTS_SUCCESS';
export const LOAD_ANNOUNCEMENTS_ERROR = 'LOAD_ANNOUNCEMENTS_ERROR';

export const CREATE_ANNOUNCEMENT_REQUEST = 'CREATE_ANNOUNCEMENT_REQUEST';
export const CREATE_ANNOUNCEMENT_SUCCESS = 'CREATE_ANNOUNCEMENT_SUCCESS';
export const CREATE_ANNOUNCEMENT_ERROR = 'CREATE_ANNOUNCEMENT_ERROR';

export const DELETE_ANNOUNCEMENT_REQUEST = 'DELETE_ANNOUNCEMENT_REQUEST';
export const DELETE_ANNOUNCEMENT_SUCCESS = 'DELETE_ANNOUNCEMENT_SUCCESS';
export const DELETE_ANNOUNCEMENT_ERROR = 'DELETE_ANNOUNCEMENT_ERROR';

export const CHANGE_ANNOUNCEMENT_REQUEST = 'CHANGE_ANNOUNCEMENT_REQUEST';
export const CHANGE_ANNOUNCEMENT_SUCCESS = 'CHANGE_ANNOUNCEMENT_SUCCESS';
export const CHANGE_ANNOUNCEMENT_ERROR = 'CHANGE_ANNOUNCEMENT_ERROR';

// POSTS (OFFER)
export const LOAD_POSTS_OFFER_REQUEST = 'LOAD_POSTS_OFFER_REQUEST';
export const LOAD_POSTS_OFFER_SUCCESS = 'LOAD_POSTS_OFFER_SUCCESS';
export const LOAD_POSTS_OFFER_ERROR = 'LOAD_POSTS_OFFER_ERROR';

export const LOAD_POSTS_OFFER_USER_REQUEST = 'LOAD_POSTS_OFFER_USER_REQUEST';
export const LOAD_POSTS_OFFER_USER_SUCCESS = 'LOAD_POSTS_OFFER_USER_SUCCESS';
export const LOAD_POSTS_OFFER_USER_ERROR = 'LOAD_POSTS_OFFER_USER_ERROR';

export const CREATE_POST_OFFER_REQUEST = 'CREATE_POST_OFFER_REQUEST';
export const CREATE_POST_OFFER_SUCCESS = 'CREATE_POST_OFFER_SUCCESS';
export const CREATE_POST_OFFER_ERROR = 'CREATE_POST_OFFER_ERROR';

export const DELETE_POST_OFFER_REQUEST = 'DELETE_POST_OFFER_REQUEST';
export const DELETE_POST_OFFER_SUCCESS = 'DELETE_POST_OFFER_SUCCESS';
export const DELETE_POST_OFFER_ERROR = 'DELETE_POST_OFFER_ERROR';

export const CHANGE_POST_OFFER_REQUEST = 'CHANGE_POST_OFFER_REQUEST';
export const CHANGE_POST_OFFER_SUCCESS = 'CHANGE_POST_OFFER_SUCCESS';
export const CHANGE_POST_OFFER_ERROR = 'CHANGE_POST_OFFER_ERROR';

// POSTS (SEARCH)
export const LOAD_POSTS_SEARCH_REQUEST = 'LOAD_POSTS_SEARCH_REQUEST';
export const LOAD_POSTS_SEARCH_SUCCESS = 'LOAD_POSTS_SEARCH_SUCCESS';
export const LOAD_POSTS_SEARCH_ERROR = 'LOAD_POSTS_SEARCH_ERROR';

export const LOAD_POSTS_SEARCH_USER_REQUEST = 'LOAD_POSTS_SEARCH_USER_REQUEST';
export const LOAD_POSTS_SEARCH_USER_SUCCESS = 'LOAD_POSTS_SEARCH_USER_SUCCESS';
export const LOAD_POSTS_SEARCH_USER_ERROR = 'LOAD_POSTS_SEARCH_USER_ERROR';

export const CREATE_POST_SEARCH_REQUEST = 'CREATE_POST_SEARCH_REQUEST';
export const CREATE_POST_SEARCH_SUCCESS = 'CREATE_POST_SEARCH_SUCCESS';
export const CREATE_POST_SEARCH_ERROR = 'CREATE_POST_SEARCH_ERROR';

export const DELETE_POST_SEARCH_REQUEST = 'DELETE_POST_SEARCH_REQUEST';
export const DELETE_POST_SEARCH_SUCCESS = 'DELETE_POST_SEARCH_SUCCESS';
export const DELETE_POST_SEARCH_ERROR = 'DELETE_POST_SEARCH_ERROR';

export const CHANGE_POST_SEARCH_REQUEST = 'CHANGE_POST_SEARCH_REQUEST';
export const CHANGE_POST_SEARCH_SUCCESS = 'CHANGE_POST_SEARCH_SUCCESS';
export const CHANGE_POST_SEARCH_ERROR = 'CHANGE_POST_SEARCH_ERROR';

// CHAT MESSAGES
export const LOAD_COMMUNITY_CHAT_MESSAGES_REQUEST =
  'LOAD_COMMUNITY_CHAT_MESSAGES_REQUEST';
export const LOAD_COMMUNITY_CHAT_MESSAGES_SUCCESS =
  'LOAD_COMMUNITY_CHAT_MESSAGES_SUCCESS';
export const LOAD_COMMUNITY_CHAT_MESSAGES_ERROR =
  'LOAD_COMMUNITY_CHAT_MESSAGES_ERROR';

export const CREATE_COMMUNITY_CHAT_MESSAGE_REQUEST =
  'CREATE_COMMUNITY_CHAT_MESSAGE_REQUEST';
export const CREATE_COMMUNITY_CHAT_MESSAGE_SUCCESS =
  'CREATE_COMMUNITY_CHAT_MESSAGE_SUCCESS';
export const CREATE_COMMUNITY_CHAT_MESSAGE_ERROR =
  'CREATE_COMMUNITY_CHAT_MESSAGE_ERROR';

export const SET_COMMUNITY_INFORMATION = 'SET_COMMUNITY_INFORMATION';
// USERS
export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_ERROR = 'LOAD_USER_ERROR';

export const LOAD_ALL_USER_REQUEST = 'LOAD_ALL_USER_REQUEST';
export const LOAD_ALL_USER_SUCCESS = 'LOAD_ALL_USER_SUCCESS';
export const LOAD_ALL_USER_ERROR = 'LOAD_ALL_USER_ERROR';

export const SET_CURRENT_USER_ID = 'SET_CURRENT_USER_ID';

//get all moderator IDs
export const SET_MODERATOR_IDS_REQUEST = 'SET_MODERATOR_IDS_REQUEST';
export const SET_MODERATOR_IDS_SUCCESS = 'SET_MODERATOR_IDS_SUCCESS';
export const SET_MODERATOR_IDS_ERROR = 'SET_MODERATOR_IDS_ERROR';
